Feature branch retrieve
DigitalOnUs/Hygieia pull request #2
Opened 2017-07-07 07:33 UTC by jasmeetkohli

# Summary

Method that retrieves all branches within a timeframe.

# Requirements

The “FeatureBranchRepository” must have a method to retrieve a list of all branches that fall within a timeframe. 

There must be appropriate unit tests for the same.

# Changes

Created methods in “FeatureBranchRepository” that retrieves all branches falling within a timeframe.

Created Unit Test Cases for the methods in “FeatureBranchRepository”.

2017-07-07 16:00 UTC, mrrusof requested changes
No major issues, just a couple of suggestions.

2017-07-07 16:00 UTC, mrrusof commented on core/src/main/java/com/capitalone/dashboard/repository/FeatureBranchRepository.java
> +    FeatureBranch findByCommitIdThatTriggeredBuild(String commitIdThatTriggeredBuild);
Could we be consistent and use word Deploy instead of Build?

2017-07-07 16:00 UTC, mrrusof commented on core/src/test/java/com/capitalone/dashboard/repository/FeatureBranchRepositoryTests.java
> +		Case 1 : let timeStamp1 < fetureOne.firstCommitTimeStamp
featureBranchOne

2017-07-07 16:00 UTC, mrrusof commented on core/src/test/java/com/capitalone/dashboard/repository/FeatureBranchRepositoryTests.java
> +	{
Could we separate testing the three methods that you introduced into dedicated test cases for each?

2017-07-10 18:31 UTC, mrrusof approved these changes

2017-07-10 20:18 UTC, oam1809 approved these changes
no findings.

2017-07-10 21:37 UTC, FranciscoAditazz approved these changes

2017-07-10 23:33 UTC, merged