1.4.3.2.1 Feature branch End Point
DigitalOnUs/Hygieia pull request #3
Opened 2017-07-14 10:23 UTC by jasmeetkohli

# Summary

API endpoint that retrieves FeatureBranches within a TimeFrame
syntax : host/api/featurebranchbytimeframe/timestamp1/timestamp2

# Requirements
There must be a Controller which defines methods for endpoints.

There must be a service and its implementation that takes care of the business logic for FeatureBranch.

There must be appropriate unit test cases for the controller and the service implementation.

# Changes

Created a controller "FeatureBranchController" which defines appropriate methods for endpoints.

Created a Service 'FeatureBranchService' and 'FeatureBranchServiceImpl' that takes care of the business logic.

Created two test files 'FeatureBranchControllerTest' and 'FeatureBranchServiceImplTest' that define test cases to verify the correct behaviour of endpoints and service implementation methods respectively.

2017-07-17 15:43 UTC, mrrusof requested changes

2017-07-17 15:43 UTC, mrrusof commented on api/src/main/java/com/capitalone/dashboard/rest/FeatureBranchController.java
> +    @RequestMapping(value = "/featurebranchbytimeframe/{timestamp1}/{timestamp2}", method = GET, produces = APPLICATION_JSON_VALUE)
Given that we are exposing feature branches and then filtering by timeframe, would it make sense to have the following syntax?

```
/feature_branches?start_timestamp=1234&end_timestamp=9876
```

2017-07-18 16:23 UTC, jaloare commented
Looks good .. I hope you can validate your code with SonarQube it is ok if not

2017-07-18 16:54 UTC, mrrusof requested changes

2017-07-18 16:54 UTC, mrrusof commented on api/src/main/java/com/capitalone/dashboard/service/FeatureBranchService.java
> +    void save(FeatureBranch featureBranch);
Who is using this?

2017-07-18 16:54 UTC, mrrusof commented on api/src/main/java/com/capitalone/dashboard/service/FeatureBranchService.java
> +    Iterable<FeatureBranch> findAll();
Who uses this?

2017-07-18 16:54 UTC, mrrusof commented on api/src/main/java/com/capitalone/dashboard/service/FeatureBranchService.java
> +    void save(FeatureBranch featureBranch);
Who uses this?

2017-07-18 16:59 UTC, mrrusof requested changes

2017-07-18 16:59 UTC, mrrusof commented on api/src/test/java/com/capitalone/dashboard/service/FeatureBranchServiceImplTest.java
> +                featureBranchService.findAll().size(),3);
Did you mean? https://stackoverflow.com/questions/11598977/get-size-of-an-iterable-in-java#11599011

2017-07-18 17:03 UTC, mrrusof requested changes

2017-07-18 17:03 UTC, mrrusof commented on api/src/main/java/com/capitalone/dashboard/rest/FeatureBranchController.java
> +                featureBranchList = new ArrayList();
Why not return HTTP 400 in this case?

2017-07-24 15:41 UTC, mrrusof approved these changes
It delivers the requested functionality.

2017-07-24 15:52 UTC, merged